include_defs('//lib/maven.defs')
include_defs('//lib/JGIT_VERSION')

maven_jar(
  name = 'jgit-archive',
  id = 'org.eclipse.jgit:org.eclipse.jgit.archive:' + VERS_WD,
  sha1 = '78925a3bfd2efd90c356a4cb54e6062711a837a5',
  license = 'jgit',
  repository = REPO_WD,
  deps = ['//lib/jgit/org.eclipse.jgit:jgit'],
  unsign = True,
  exclude = [
    'about.html',
    'plugin.properties',
  ],
 )
