include_defs('//lib/maven.defs')
include_defs('//lib/JGIT_VERSION')

maven_jar(
  name = 'jgit-servlet',
  id = 'org.eclipse.jgit:org.eclipse.jgit.http.server:' + VERS_WD,
  sha1 = 'd739dfdce85602a4457b284f38d517de31dd50c2',
  license = 'jgit',
  repository = REPO_WD,
  deps = ['//lib/jgit/org.eclipse.jgit:jgit'],
  unsign = True,
  exclude = [
    'about.html',
    'plugin.properties',
  ],
)
