include_defs('//lib/maven.defs')
include_defs('//lib/JGIT_VERSION')

maven_jar(
  name = 'jgit-servlet',
  id = 'org.eclipse.jgit:org.eclipse.jgit.http.server:' + VERS_WD,
  sha1 = 'ae8040ee8e24f44b2e8ef6061c4b7b5eb1f1566a',
  license = 'jgit',
  repository = REPO_WD,
  deps = ['//lib/jgit/org.eclipse.jgit:jgit'],
  unsign = True,
  exclude = [
    'about.html',
    'plugin.properties',
  ],
)
