include_defs('//lib/maven.defs')

maven_jar(
  name = 'equalsverifier',
  id = 'nl.jqno.equalsverifier:equalsverifier:1.3.1',
  sha1 = '3c8d6837afa9de0290927582cdd904d8d355c66a',
  license = 'DO_NOT_DISTRIBUTE',
  deps = [
    '//lib/easymock:cglib-2_2',
    '//lib/easymock:objenesis',
  ],
)


