java_library(
    name = "equalsverifier",
    visibility = ["//visibility:public"],
    exports = ["@equalsverifier//jar"],
    runtime_deps = [
        "//lib/easymock:cglib-2_2",
        "//lib/easymock:objenesis",
    ],
)
