[java_library(
  name = n,
  exports = ['@%s//jar' % n.replace("-", "_")],
  visibility = ["//visibility:public"],
) for n in [
  'javax-validation',
  'dev',
  'user',
  'jsinterop-annotations',
  'ant',
  'colt',
  'tapestry',
  'w3c-css-sac',
  'jsr305'
]]
