include_defs('//lib/maven.defs')
include_defs('//lib/JGIT_VERSION')

maven_jar(
  name = 'junit',
  id = 'org.eclipse.jgit:org.eclipse.jgit.junit:' + VERS_WD,
  sha1 = 'afcecd906a43d04cdbd7d2a85d20ff0a47bbde8bx',
  license = 'DO_NOT_DISTRIBUTE',
  repository = REPO_WD,
  unsign = True,
  deps = ['//lib/jgit/org.eclipse.jgit:jgit'],
)
